[CAR_TESTS] Added carServiceTests
jv-jun23-team3/car-sharing-app pull request #30
Opened 2023-10-04 13:09 UTC by OlegTuryk

2023-10-04 14:26 UTC, Zel1oy approved these changes
LEGITIME

2023-10-04 20:05 UTC, padu12 requested changes
Nice tests! Let's resolve all magic numbers. Please, pay more attention to magic numbers in future test

2023-10-04 20:05 UTC, padu12 commented on src/test/java/ua/mate/team3/carsharingapp/service/CarServiceTest.java
> +        CarDto actual = carService.update(1L, createCarRequestDto);
Magic number

2023-10-04 20:05 UTC, padu12 commented on src/test/java/ua/mate/team3/carsharingapp/service/CarServiceTest.java
> +        verify(carRepository, times(1)).deleteById(1L);
Magic numbers

2023-10-04 20:05 UTC, padu12 commented on src/test/java/ua/mate/team3/carsharingapp/service/CarServiceTest.java
> +        CarDto actual = carService.getById(1L);
Magic numbers

2023-10-04 20:05 UTC, padu12 commented on src/test/java/ua/mate/team3/carsharingapp/service/CarServiceTest.java
> +                new PageImpl<>(List.of(testCar), pageable, 1);
Magic numbers

2023-10-04 20:05 UTC, padu12 commented on src/test/java/ua/mate/team3/carsharingapp/controller/CarControllerTest.java
> +                        get("/cars/1")
Magic number

2023-10-04 20:05 UTC, padu12 commented on src/test/java/ua/mate/team3/carsharingapp/controller/CarControllerTest.java
> +        mockMvc.perform(delete("/cars/1"))
Magic number

2023-10-04 20:05 UTC, padu12 commented on src/test/java/ua/mate/team3/carsharingapp/controller/CarControllerTest.java
> +        MvcResult mvcResult = mockMvc.perform(put("/cars/1")
Magic number

2023-10-05 10:10 UTC, padu12 approved these changes

2023-10-05 10:11 UTC, SaiyaJ1N approved these changes

2023-10-05 10:12 UTC, merged